// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a83be55fe8abf333 "Fragment OS (copy)", do not edit manually */
"use client";

// virtual:d-ashboard-animation
/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/Lf12a3SY2G5ZoAerGF9E/YQtja8lI8R16ftTXN25H/SzgLjmedv.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	ComponentViewportProvider,
	cx as cx2,
	forwardLoader,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/bdcs7VcWMBbaa15zGOw2/IwAYiVgdMHwXUBHdAAuT/FQG9gqwJ3.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getLoadingLazyAtYPosition,
	Image as Image1,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-v33aV";
var variantClassNames = {
	Irhlv680z: "framer-v-oipedc",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "Irhlv680z",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Image1
						{...restProps}
						{...gestureHandlers}
						background={{
							alt: "Fragments OS",
							fit: "fill",
							intrinsicHeight: 1177,
							intrinsicWidth: 1e3,
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							pixelHeight: 1177,
							pixelWidth: 1e3,
							sizes: componentViewport?.width || "100vw",
							src: "https://framerusercontent.com/images/wiCRPDiL9RKlRbfWr5pd2gtbwLs.png?width=1000&height=1177",
							srcSet:
								"https://framerusercontent.com/images/wiCRPDiL9RKlRbfWr5pd2gtbwLs.png?scale-down-to=1024&width=1000&height=1177 870w,https://framerusercontent.com/images/wiCRPDiL9RKlRbfWr5pd2gtbwLs.png?width=1000&height=1177 1000w",
						}}
						className={cx(
							scopingClassNames,
							"framer-oipedc",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"Irhlv680z"}
						ref={refBinding}
						style={{
							...style,
						}}
					/>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-v33aV.framer-jixpq4, .framer-v33aV .framer-jixpq4 { display: block; }",
	".framer-v33aV.framer-oipedc { height: 1177px; position: relative; width: 1000px; }",
];
var FramerFQG9gqwJ3 = withCSS(Component, css, "framer-v33aV");
var stdin_default = FramerFQG9gqwJ3;
FramerFQG9gqwJ3.displayName = "Dashbaord";
FramerFQG9gqwJ3.defaultProps = {
	height: 1177,
	width: 1e3,
};
addFonts(
	FramerFQG9gqwJ3,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/Lf12a3SY2G5ZoAerGF9E/YQtja8lI8R16ftTXN25H/SzgLjmedv.js
var DashbaordFonts = getFonts(stdin_default);
var MotionDivWithFX = withFX(motion2.div);
var serializationHash2 = "framer-zmz4E";
var variantClassNames2 = {
	nkbVkpgrZ: "framer-v-qqtb32",
};
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const { style, className, layoutId, variant, ...restProps } =
		getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "nkbVkpgrZ",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-qqtb32",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"nkbVkpgrZ"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<MotionDivWithFX
							__framer__spring={{
								damping: 60,
								delay: 0,
								duration: 0.3,
								ease: [0.44, 0, 0.56, 1],
								mass: 1,
								stagger: 0,
								stiffness: 500,
								type: "spring",
							}}
							__framer__styleTransformEffectEnabled={true}
							__framer__transformTargets={[
								{
									target: {
										opacity: 1,
										rotate: 0,
										rotateX: 24,
										rotateY: 0,
										scale: 0.5,
										skewX: 0,
										skewY: 0,
										x: 0,
										y: 0,
									},
								},
								{
									target: {
										opacity: 1,
										rotate: 0,
										rotateX: 0,
										rotateY: 0,
										scale: 1,
										skewX: 0,
										skewY: 0,
										x: 0,
										y: 0,
									},
								},
							]}
							__framer__transformTrigger={"onInView"}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-1fnn0a9"}
							data-border={true}
							data-framer-name={"Screenshot"}
							layoutDependency={layoutDependency}
							layoutId={"DlwzuypJt"}
							style={{
								"--border-bottom-width": "4px",
								"--border-color":
									"var(--token-818a283b-450e-452c-a8af-6b81d42f4181, rgb(18, 18, 18))",
								"--border-left-width": "4px",
								"--border-right-width": "4px",
								"--border-style": "solid",
								"--border-top-width": "4px",
								backgroundColor: "rgb(255, 255, 255)",
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								transformPerspective: 1200,
							}}
						>
							<ComponentViewportProvider
								height={1176.3478}
								width={"1000px"}
								y={(componentViewport?.y || 0) + 0 + 0 + 0}
							>
								<SmartComponentScopedContainer
									className={"framer-1abhmzj-container"}
									layoutDependency={layoutDependency}
									layoutId={"jDo3NeK_Y-container"}
									nodeId={"jDo3NeK_Y"}
									rendersWithMotion={true}
									scopeId={"SzgLjmedv"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										id: "jDo3NeK_Y",
										layoutId: "jDo3NeK_Y",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</MotionDivWithFX>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-zmz4E.framer-1z0173z, .framer-zmz4E .framer-1z0173z { display: block; }",
	".framer-zmz4E.framer-qqtb32 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 120px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1120px; }",
	".framer-zmz4E .framer-1fnn0a9 { aspect-ratio: 1.4062991800221742 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 711px); overflow: hidden; position: relative; width: 1000px; will-change: var(--framer-will-change-override, transform); }",
	".framer-zmz4E .framer-1abhmzj-container { flex: none; height: 1176px; left: 0px; position: absolute; right: 0px; top: 0px; }",
	'.framer-zmz4E[data-border="true"]::after, .framer-zmz4E [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerSzgLjmedv = withCSS2(Component2, css2, "framer-zmz4E");
var stdin_default2 = FramerSzgLjmedv;
FramerSzgLjmedv.displayName = "DAshboard animation";
FramerSzgLjmedv.defaultProps = {
	height: 711,
	width: 1120,
};
addFonts2(
	FramerSzgLjmedv,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...DashbaordFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerSzgLjmedv.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:d-ashboard-animation
import { WithFramerBreakpoints } from "unframer";

// virtual:__routes
var routes = {
	LqvzCkTjw: {
		path: "/style-guide",
	},
	Vrb_2Mu_N: {
		path: "/404",
	},
	augiA20Il: {
		path: "/",
	},
};

// virtual:d-ashboard-animation
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a83be55fe8abf333dd1dd70aeb1a90bd31d7987ea1c600fac9e5533b4f7dd434"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders DAshboardAnimationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a83be55fe8abf333dd1dd70aeb1a90bd31d7987ea1c600fac9e5533b4f7dd434"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var d_ashboard_animation_default = ComponentWithRoot;
export { d_ashboard_animation_default as default };
